name: Build and deploy

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Set the version number in main.ts
        run: |
          export SHORT_HASH=$(echo $GITHUB_SHA | cut -c-7)
          sed -i "/version:/s/\"\"/\"$SHORT_HASH\"/" src/main.ts
        # sed looks for version: and then substitutes "" for the short commit hash
      
      - name: Setup Node
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 16.x
          
      - name: Install dependencies and build
        run: |
          npm ci
          npm run build
      
      - name: Setup GPG signing key
        uses: crazy-max/ghaction-import-gpg@v4.1.0
        with:
          gpg_private_key: ${{secrets.GPG_PRIVATE_KEY}}
          passphrase: ${{secrets.PASSPHRASE}}
          git_user_signingkey: true
          git_commit_gpgsign: true
          
      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4.2.3
        with:
          git-config-name: ${{github.repository_owner}}
          git-config-email: ${{github.event.repository.owner.id}}+${{github.repository_owner}}@users.noreply.github.com
          branch: gh-pages
          folder: public
          clean: true
